import { execFile } from 'child_process';
import util from 'util';
import fs from 'fs';
import path from 'path';

const execFilePromise = util.promisify(execFile);

export interface YtDlpMediaFormat {
  quality: string;
  extension: string;
  url: string;
  directUrl?: string;
  size?: string;
  isAudioOnly?: boolean;
  resolution?: string;
  fps?: number;
  formatId?: string;
}

export interface YtDlpSubtitleTrack {
  lang: string;
  name: string;
  url: string;
  downloadUrl?: string;
  type: 'official' | 'auto' | 'danmaku';
  isAutoGenerated: boolean;
  isDanmaku?: boolean;
  ext: string;
  author?: string;
}

export interface YtDlpExtractResult {
  success: boolean;
  title: string;
  thumbnail: string;
  duration: number | string;
  durationFormatted?: string;
  source: string;
  author?: string;
  views?: string | number;
  medias: YtDlpMediaFormat[];
  subtitles?: YtDlpSubtitleTrack[];
  videoUrl?: string;
  directUrl?: string;
  audioUrl?: string;
  audioDirectUrl?: string;
  error?: string;
}

/**
 * Finds the best available path for yt-dlp binary
 */
export async function ensureYtDlpBinary(): Promise<string> {
  const customPath = process.env.YTDLP_PATH;
  if (customPath && fs.existsSync(customPath)) {
    try {
      fs.chmodSync(customPath, 0o755);
    } catch (_) {}
    return customPath;
  }

  const localBinLinux = path.join(process.cwd(), 'bin', 'yt-dlp_linux');
  if (fs.existsSync(localBinLinux)) {
    try {
      const stat = fs.statSync(localBinLinux);
      if (stat.size > 5000000) {
        fs.chmodSync(localBinLinux, 0o755);
        return localBinLinux;
      }
    } catch (_) {}
  }

  const localBin = path.join(process.cwd(), 'bin', 'yt-dlp');
  if (fs.existsSync(localBin)) {
    try {
      const stat = fs.statSync(localBin);
      if (stat.size > 1000000) {
        fs.chmodSync(localBin, 0o755);
        return localBin;
      }
    } catch (_) {}
  }

  const localBinWin = path.join(process.cwd(), 'bin', 'yt-dlp.exe');
  if (fs.existsSync(localBinWin)) {
    return localBinWin;
  }

  const usrLocalBin = '/usr/local/bin/yt-dlp';
  if (fs.existsSync(usrLocalBin)) {
    return usrLocalBin;
  }

  // Attempt auto-downloading yt-dlp_linux or yt-dlp if not found
  try {
    const binDir = path.join(process.cwd(), 'bin');
    fs.mkdirSync(binDir, { recursive: true });
    console.log('[yt-dlp Service] Downloading official yt-dlp release binary...');
    const dlRes = await fetch('https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux');
    if (dlRes.ok) {
      const buf = Buffer.from(await dlRes.arrayBuffer());
      fs.writeFileSync(localBinLinux, buf);
      fs.chmodSync(localBinLinux, 0o755);
      console.log('[yt-dlp Service] Successfully installed yt-dlp_linux binary.');
      return localBinLinux;
    }
  } catch (dlErr: any) {
    console.warn('[yt-dlp Service] Auto-download failed:', dlErr?.message || dlErr);
  }

  return 'yt-dlp';
}

export function getYtDlpPath(): string {
  const customPath = process.env.YTDLP_PATH;
  if (customPath && fs.existsSync(customPath)) {
    try {
      fs.chmodSync(customPath, 0o755);
    } catch (_) {}
    return customPath;
  }

  const localBinLinux = path.join(process.cwd(), 'bin', 'yt-dlp_linux');
  if (fs.existsSync(localBinLinux)) {
    try {
      fs.chmodSync(localBinLinux, 0o755);
    } catch (_) {}
    return localBinLinux;
  }

  const localBin = path.join(process.cwd(), 'bin', 'yt-dlp');
  if (fs.existsSync(localBin)) {
    try {
      fs.chmodSync(localBin, 0o755);
    } catch (_) {}
    return localBin;
  }

  const localBinWin = path.join(process.cwd(), 'bin', 'yt-dlp.exe');
  if (fs.existsSync(localBinWin)) {
    return localBinWin;
  }

  const usrLocalBin = '/usr/local/bin/yt-dlp';
  if (fs.existsSync(usrLocalBin)) {
    return usrLocalBin;
  }

  return 'yt-dlp';
}

function formatBytes(bytes?: number): string | undefined {
  if (!bytes || isNaN(bytes) || bytes <= 0) return undefined;
  const mb = bytes / (1024 * 1024);
  if (mb >= 1024) {
    return `${(mb / 1024).toFixed(2).replace('.', ',')} GB`;
  }
  return `${mb.toFixed(1).replace('.', ',')} MB`;
}

function formatDurationSeconds(seconds?: number): string {
  if (!seconds || isNaN(seconds) || seconds <= 0) return '0:00';
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  const hours = Math.floor(mins / 60);
  const remMins = mins % 60;
  if (hours > 0) {
    return `${hours}:${remMins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

function formatTimeSrt(seconds: number): string {
  if (isNaN(seconds) || seconds < 0) seconds = 0;
  const pad = (num: number, size = 2) => num.toString().padStart(size, '0');
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);
  return `${pad(hrs)}:${pad(mins)}:${pad(secs)},${pad(ms, 3)}`;
}

/**
 * Converts various subtitle formats (Bilibili JSON, WebVTT, YouTube XML/TTML, Danmaku XML) into clean SRT text
 */
export function convertSubtitleToSrt(rawContent: string): string {
  if (!rawContent || !rawContent.trim()) return '';

  const trimmed = rawContent.trim();

  // 1. Check if Bilibili JSON Subtitle format { font_size, body: [ { from, to, content } ] }
  if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
    try {
      const parsed = JSON.parse(trimmed);
      const body = parsed.body || parsed.data?.body || (Array.isArray(parsed) ? parsed : null);
      if (Array.isArray(body) && body.length > 0) {
        return body
          .map((item: any, index: number) => {
            const startSec = typeof item.from === 'number' ? item.from : parseFloat(item.from || '0');
            const endSec = typeof item.to === 'number' ? item.to : parseFloat(item.to || (startSec + 2).toString());
            const text = (item.content || '').trim();
            if (!text) return '';
            return `${index + 1}\n${formatTimeSrt(startSec)} --> ${formatTimeSrt(endSec)}\n${text}\n`;
          })
          .filter(Boolean)
          .join('\n');
      }
    } catch (_) {}
  }

  // 2. Check if YouTube JSON3 format
  if (trimmed.startsWith('{') && trimmed.includes('"events"')) {
    try {
      const parsed = JSON.parse(trimmed);
      if (Array.isArray(parsed.events)) {
        let srtIndex = 1;
        const cues: string[] = [];
        for (const ev of parsed.events) {
          if (!ev.segs || !Array.isArray(ev.segs)) continue;
          const text = ev.segs.map((s: any) => s.utf8 || '').join('').trim();
          if (!text || text === '\n') continue;
          const startSec = (ev.tStartMs || 0) / 1000;
          const durSec = (ev.dDurationMs || 2000) / 1000;
          const endSec = startSec + durSec;
          cues.push(`${srtIndex++}\n${formatTimeSrt(startSec)} --> ${formatTimeSrt(endSec)}\n${text}\n`);
        }
        if (cues.length > 0) return cues.join('\n');
      }
    } catch (_) {}
  }

  // 3. Check if WebVTT
  if (trimmed.startsWith('WEBVTT') || trimmed.includes('-->')) {
    // Convert WebVTT timestamps (00:00:00.000) to SRT timestamps (00:00:00,000)
    let srtText = trimmed
      .replace(/^WEBVTT[^\n]*\n+/i, '')
      .replace(/(\d{2}:\d{2}:\d{2})\.(\d{3})/g, '$1,$2')
      .replace(/(\d{2}:\d{2})\.(\d{3})/g, '00:$1,$2');
    return srtText;
  }

  // 4. Check if YouTube XML / TTML (<text start="1.2" dur="3.4">...</text>)
  if (trimmed.includes('<text') || trimmed.includes('<p begin=')) {
    const textMatches = [...trimmed.matchAll(/<text[^>]*start="([^"]+)"[^>]*(?:dur="([^"]+)")?[^>]*>([\s\S]*?)<\/text>/gi)];
    if (textMatches.length > 0) {
      return textMatches
        .map((m, idx) => {
          const startSec = parseFloat(m[1] || '0');
          const durSec = parseFloat(m[2] || '2.0');
          const endSec = startSec + durSec;
          const text = m[3]
            .replace(/&amp;/g, '&')
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>')
            .replace(/&quot;/g, '"')
            .replace(/&#39;/g, "'")
            .replace(/<[^>]+>/g, '')
            .trim();
          if (!text) return '';
          return `${idx + 1}\n${formatTimeSrt(startSec)} --> ${formatTimeSrt(endSec)}\n${text}\n`;
        })
        .filter(Boolean)
        .join('\n');
    }
  }

// 5. Check if Bilibili Danmaku XML (<d p="12.345,1,25,16777215,...">Comment</d>)
  if (trimmed.includes('<d p=')) {
    const dMatches = [...trimmed.matchAll(/<d\s+p="([^"]+)">([\s\S]*?)<\/d>/gi)];
    if (dMatches.length > 0) {
      let idx = 1;
      const cues: string[] = [];
      for (const m of dMatches) {
        const pParams = m[1].split(',');
        const startSec = parseFloat(pParams[0] || '0');
        const durSec = 3.5;
        const endSec = startSec + durSec;
        const text = m[2]
          .replace(/&amp;/g, '&')
          .replace(/&lt;/g, '<')
          .replace(/&gt;/g, '>')
          .replace(/&quot;/g, '"')
          .replace(/&#39;/g, "'")
          .trim();
        if (!text) continue;
        cues.push(`${idx++}\n${formatTimeSrt(startSec)} --> ${formatTimeSrt(endSec)}\n${text}\n`);
      }
      if (cues.length > 0) return cues.join('\n');
    }
  }

  return trimmed;
}

const DEFAULT_BILIBILI_SESSDATA = '3cdb128a%2C1803820138%2C4c6db%2A92CjAaFsbqqqzk6bQrYmrM6OZt44VhENf5mHPReQTOrOZyd6QIdT8ifWO6JhOegbq0qkUSVjZwUmVacDN4MzJFYUlscXNYb0Z0cmhtT05DYUxQbmNKZ1BVb0FVUTVhRVVMZ2lrbVE0TkZ6eUxDeHJNSzRJb1hHUDhsY2FSUVBTUFdzWkdmc25fcUZ3IIEC';

let cachedBiliCookies: { cookieStr: string; timestamp: number } | null = null;

/**
 * Get active Bilibili cookies (buvid3/buvid4/SESSDATA) to access full 1080P video & AI subtitles
 */
export async function getBilibiliCookieHeader(): Promise<string> {
  const now = Date.now();
  const sessdata = process.env.BILIBILI_SESSDATA || DEFAULT_BILIBILI_SESSDATA;

  if (cachedBiliCookies && now - cachedBiliCookies.timestamp < 3600000) {
    return cachedBiliCookies.cookieStr;
  }

  try {
    const res = await fetch('https://api.bilibili.com/x/frontend/finger/spi', {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Referer': 'https://www.bilibili.com/',
      },
      signal: AbortSignal.timeout(5000),
    });
    if (res.ok) {
      const json = await res.json();
      if (json.data && json.data.b_3) {
        const cookieStr = `buvid3=${json.data.b_3}; buvid4=${json.data.b_4 || ''}; SESSDATA=${sessdata}; CURRENT_FNVAL=4048`;
        cachedBiliCookies = { cookieStr, timestamp: now };
        return cookieStr;
      }
    }
  } catch (_) {}

  return `buvid3=B9E37E5A-DDBB-C36C-1836-7302257A383E16698infoc; SESSDATA=${sessdata}; CURRENT_FNVAL=4048`;
}

/**
 * Ensure Netscape Cookie file exists for yt-dlp to bypass Bilibili HTTP 412 & fetch AI subtitles
 */
export async function ensureBilibiliCookieFile(): Promise<string> {
  const cookieFilePath = '/tmp/bili_cookies.txt';
  const sessdata = process.env.BILIBILI_SESSDATA || DEFAULT_BILIBILI_SESSDATA;
  let b3 = 'B9E37E5A-DDBB-C36C-1836-7302257A383E16698infoc';
  let b4 = '';

  try {
    const res = await fetch('https://api.bilibili.com/x/frontend/finger/spi', {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Referer': 'https://www.bilibili.com/',
      },
      signal: AbortSignal.timeout(5000),
    });
    if (res.ok) {
      const json = await res.json();
      if (json.data && json.data.b_3) {
        b3 = json.data.b_3;
        b4 = json.data.b_4 || '';
      }
    }
  } catch (_) {}

  const content = `# Netscape HTTP Cookie File
.bilibili.com	TRUE	/	FALSE	2147483647	buvid3	${b3}
.bilibili.com	TRUE	/	FALSE	2147483647	buvid4	${b4}
.bilibili.com	TRUE	/	FALSE	2147483647	SESSDATA	${sessdata}
.bilibili.com	TRUE	/	FALSE	2147483647	CURRENT_FNVAL	4048
`;
  try {
    fs.writeFileSync(cookieFilePath, content, 'utf-8');
  } catch (_) {}

  return cookieFilePath;
}

/**
 * Ensure Netscape Cookie file exists for Douyin with authentic session credentials from DouyinPhien
 */
export async function ensureDouyinCookieFile(): Promise<string> {
  const cookieFilePath = '/tmp/douyin_cookies.txt';
  const content = `# Netscape HTTP Cookie File
.douyin.com	TRUE	/	FALSE	2147483647	sessionid	a8e9d1361f4069df67f6b4977d990f61
.douyin.com	TRUE	/	FALSE	2147483647	sessionid_ss	a8e9d1361f4069df67f6b4977d990f61
.douyin.com	TRUE	/	FALSE	2147483647	sid_tt	a8e9d1361f4069df67f6b4977d990f61
.douyin.com	TRUE	/	FALSE	2147483647	passport_csrf_token	bc1ed3b037464d180effb6b4ac6401af
.douyin.com	TRUE	/	FALSE	2147483647	odin_tt	508f7f7bb8d158fcc476a200dbb56e36c86e9c31353ac20e74bd0159b8f57f304344794b9f5e113419e873e82f6d99ef8850e54a84f1b5beb569b01c143a6b0554967720776020e19b0f641531ad4f9f
.douyin.com	TRUE	/	FALSE	2147483647	d_ticket	cc5ee97c28189edc2ec708ee0889c0c3a6b0e
.douyin.com	TRUE	/	FALSE	2147483647	uid_tt	4d9dc40e6021a95344112a737c9d8aef
.douyin.com	TRUE	/	FALSE	2147483647	uid_tt_ss	4d9dc40e6021a95344112a737c9d8aef
.iesdouyin.com	TRUE	/	FALSE	2147483647	sessionid	a8e9d1361f4069df67f6b4977d990f61
.iesdouyin.com	TRUE	/	FALSE	2147483647	sessionid_ss	a8e9d1361f4069df67f6b4977d990f61
.snssdk.com	TRUE	/	FALSE	2147483647	sessionid	a8e9d1361f4069df67f6b4977d990f61
.amemv.com	TRUE	/	FALSE	2147483647	sessionid	a8e9d1361f4069df67f6b4977d990f61
`;
  try {
    fs.writeFileSync(cookieFilePath, content, 'utf-8');
  } catch (_) {}
  return cookieFilePath;
}

/**
 * Resolves redirect URLs for shortlinks (b23.tv, vt.tiktok.com, vm.tiktok.com, fb.watch, youtu.be)
 */
export async function resolveCanonicalUrl(rawUrl: string): Promise<string> {
  const cleanUrlMatch = rawUrl.match(/https?:\/\/[^\s]+/i);
  let targetUrl = cleanUrlMatch ? cleanUrlMatch[0] : rawUrl.trim();

  // 1. Resolve Bilibili b23.tv shortlink
  if (targetUrl.includes('b23.tv/')) {
    try {
      const res = await fetch(targetUrl, {
        method: 'GET',
        redirect: 'follow',
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        },
        signal: AbortSignal.timeout(6000),
      });
      if (res.url && res.url !== targetUrl) {
        console.log(`[URL Resolver] Resolved b23.tv shortlink: ${targetUrl} -> ${res.url}`);
        targetUrl = res.url;
      }
    } catch (_) {}
  }
  // 2. Resolve TikTok shortlinks (vt.tiktok.com, vm.tiktok.com)
  else if (targetUrl.includes('vt.tiktok.com/') || targetUrl.includes('vm.tiktok.com/')) {
    try {
      const res = await fetch(targetUrl, {
        method: 'GET',
        redirect: 'follow',
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        },
        signal: AbortSignal.timeout(6000),
      });
      if (res.url && res.url !== targetUrl) {
        console.log(`[URL Resolver] Resolved TikTok shortlink: ${targetUrl} -> ${res.url}`);
        targetUrl = res.url;
      }
    } catch (_) {}
  }

  return targetUrl;
}

/**
 * Direct Bilibili API extractor for Video Stream, Audio, and Metadata
 */
export async function extractBilibiliDirect(urlOrBvid: string): Promise<YtDlpExtractResult> {
  try {
    let bvid = '';
    const bvMatch = urlOrBvid.match(/BV1[a-zA-Z0-9]{9}|BV[a-zA-Z0-9]{10}/i);
    if (bvMatch) {
      bvid = bvMatch[0];
    } else {
      const resolved = await resolveCanonicalUrl(urlOrBvid);
      const m = resolved.match(/BV1[a-zA-Z0-9]{9}|BV[a-zA-Z0-9]{10}/i);
      if (m) bvid = m[0];
    }

    if (!bvid) {
      return {
        success: false,
        title: '',
        thumbnail: '',
        duration: 0,
        source: 'Bilibili',
        medias: [],
        error: 'Không tìm thấy mã video Bilibili (BVID) hợp lệ trong đường dẫn.',
      };
    }

    const cookieHeader = await getBilibiliCookieHeader();
    console.log(`[Bilibili Native Extractor] Fetching view info for BVID: ${bvid}...`);

    const viewRes = await fetch(`https://api.bilibili.com/x/web-interface/view?bvid=${bvid}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Referer': 'https://www.bilibili.com/',
        'Cookie': cookieHeader,
      },
      signal: AbortSignal.timeout(7000),
    });

    if (!viewRes.ok) {
      return {
        success: false,
        title: '',
        thumbnail: '',
        duration: 0,
        source: 'Bilibili',
        medias: [],
        error: `Máy chủ Bilibili trả về mã lỗi HTTP ${viewRes.status}.`,
      };
    }

    const viewJson = await viewRes.json();
    if (viewJson.code !== 0 || !viewJson.data) {
      const errorMsg = viewJson.code === -404 || viewJson.message?.includes('木有') || viewJson.message?.includes('不存在')
        ? 'Video Bilibili này không tồn tại, đã bị tác giả xóa hoặc bị giới hạn riêng tư/khu vực.'
        : (viewJson.message || 'Không thể lấy thông tin video Bilibili.');
      return {
        success: false,
        title: '',
        thumbnail: '',
        duration: 0,
        source: 'Bilibili',
        medias: [],
        error: errorMsg,
      };
    }

    const vData = viewJson.data;
    const cid = vData.cid || (vData.pages?.[0]?.cid);
    const title = vData.title || `Bilibili Video (${bvid})`;
    let pic = vData.pic || '';
    if (pic.startsWith('//')) pic = `https:${pic}`;
    const duration = vData.duration || 0;
    const author = vData.owner?.name || undefined;
    const views = vData.stat?.view ? Number(vData.stat.view).toLocaleString('vi-VN') : undefined;

    // Fetch playurl streams
    const playUrlRes = await fetch(`https://api.bilibili.com/x/player/playurl?bvid=${bvid}&cid=${cid}&qn=80&fnval=0&fnver=0&fourk=1`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Referer': 'https://www.bilibili.com/',
        'Cookie': cookieHeader,
      },
      signal: AbortSignal.timeout(7000),
    });

    const medias: YtDlpMediaFormat[] = [];
    if (playUrlRes.ok) {
      const playJson = await playUrlRes.json();
      if (playJson.code === 0 && playJson.data?.durl) {
        const durls = playJson.data.durl;
        for (const item of durls) {
          if (item.url) {
            const qualityNum = playJson.data.quality || 64;
            let label = 'HD (720p)';
            if (qualityNum >= 80) label = 'Full HD (1080p)';
            else if (qualityNum === 64) label = 'HD (720p)';
            else if (qualityNum <= 32) label = 'SD (360p)';

            medias.push({
              quality: label,
              extension: 'mp4',
              url: item.url,
              directUrl: `/api/proxy-video?url=${encodeURIComponent(item.url)}`,
              size: formatBytes(item.size),
              isAudioOnly: false,
            });

            if (Array.isArray(item.backup_url)) {
              for (let i = 0; i < item.backup_url.length; i++) {
                const bUrl = item.backup_url[i];
                if (bUrl && medias.length < 3) {
                  medias.push({
                    quality: `${label} - Máy chủ dự phòng ${i + 1}`,
                    extension: 'mp4',
                    url: bUrl,
                    directUrl: `/api/proxy-video?url=${encodeURIComponent(bUrl)}`,
                    size: formatBytes(item.size),
                    isAudioOnly: false,
                  });
                }
              }
            }
          }
        }
      }
    }

    // Fetch official and AI subtitles
    const subtitles = await fetchBilibiliOfficialSubtitles(bvid);

    const primaryVideo = medias[0];
    return {
      success: true,
      title,
      thumbnail: pic,
      duration,
      durationFormatted: formatDurationSeconds(duration),
      source: 'Bilibili Direct API',
      author,
      views,
      medias,
      subtitles,
      videoUrl: primaryVideo?.url || '',
      directUrl: primaryVideo?.directUrl || primaryVideo?.url || '',
    };
  } catch (err: any) {
    return {
      success: false,
      title: '',
      thumbnail: '',
      duration: 0,
      source: 'Bilibili',
      medias: [],
      error: `Lỗi bóc tách Bilibili: ${err.message || err}`,
    };
  }
}

/**
 * Direct Bilibili API extractor for official subtitles (CC / Lời thoại chuẩn)
 */
export async function fetchBilibiliOfficialSubtitles(urlOrBvid: string): Promise<YtDlpSubtitleTrack[]> {
  try {
    let bvid = '';
    const bvMatch = urlOrBvid.match(/BV1[a-zA-Z0-9]{9}|BV[a-zA-Z0-9]{10}/i);
    if (bvMatch) {
      bvid = bvMatch[0];
    } else if (urlOrBvid.includes('b23.tv')) {
      // Resolve shortlink
      try {
        const res = await fetch(urlOrBvid, {
          method: 'GET',
          redirect: 'follow',
          headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
          }
        });
        const destUrl = res.url || '';
        const m = destUrl.match(/BV1[a-zA-Z0-9]{9}|BV[a-zA-Z0-9]{10}/i);
        if (m) bvid = m[0];
      } catch (_) {}
    }

    if (!bvid) return [];

    console.log(`[Bilibili Subtitle API] Fetching official subtitles for BVID: ${bvid}...`);
    const cookieHeader = await getBilibiliCookieHeader();

    const viewRes = await fetch(`https://api.bilibili.com/x/web-interface/view?bvid=${bvid}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Referer': 'https://www.bilibili.com/',
        'Cookie': cookieHeader,
      },
      signal: AbortSignal.timeout(6000),
    });

    if (!viewRes.ok) return [];
    const json = await viewRes.json();
    if (json.code !== 0 || !json.data) return [];

    const cid = json.data.cid;
    const subList = json.data.subtitle?.list || [];

    const tracks: YtDlpSubtitleTrack[] = [];

    for (const item of subList) {
      if (item.subtitle_url) {
        let subUrl = item.subtitle_url;
        if (subUrl.startsWith('//')) subUrl = `https:${subUrl}`;
        const isAuto = item.is_machine === 1 || item.lan_doc?.includes('自动') || item.lan_doc?.includes('AI');
        const langName = item.lan_doc || item.lan || 'Tiếng Trung (Phụ đề gốc)';

        tracks.push({
          lang: item.lan || 'zh-CN',
          name: `${langName} ${isAuto ? '(AI Tự động)' : '(Phụ đề chuẩn)'}`,
          url: subUrl,
          downloadUrl: `/api/proxy-subtitle?url=${encodeURIComponent(subUrl)}&lang=${encodeURIComponent(item.lan || 'zh')}&type=${isAuto ? 'auto' : 'official'}`,
          type: isAuto ? 'auto' : 'official',
          isAutoGenerated: isAuto,
          isDanmaku: false,
          ext: 'json',
          author: item.author?.name || undefined,
        });
      }
    }

    // Priority 1: Bilibili player wbi v2 API (provides the exact video AI subtitles matching the specific cid/episode)
    if (cid) {
      try {
        const wbiRes = await fetch(`https://api.bilibili.com/x/player/wbi/v2?bvid=${bvid}&cid=${cid}`, {
          headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
            'Referer': 'https://www.bilibili.com/',
            'Cookie': cookieHeader,
          },
          signal: AbortSignal.timeout(5000),
        });
        if (wbiRes.ok) {
          const wbiJson = await wbiRes.json();
          const wbiSubs = wbiJson.data?.subtitle?.subtitles || [];
          for (const item of wbiSubs) {
            if (item.subtitle_url && !tracks.some(t => t.url === item.subtitle_url || t.lang === item.lan)) {
              let subUrl = item.subtitle_url;
              if (subUrl.startsWith('//')) subUrl = `https:${subUrl}`;
              const isAuto = item.is_machine === 1 || item.lan_doc?.includes('自动') || item.lan_doc?.includes('AI') || item.lan?.includes('ai');
              const langName = item.lan_doc || item.lan || 'Tiếng Trung (Phụ đề gốc)';
              tracks.push({
                lang: item.lan || 'zh-CN',
                name: `${langName} ${isAuto ? '(AI Tự động)' : '(Phụ đề chuẩn)'}`,
                url: subUrl,
                downloadUrl: `/api/proxy-subtitle?url=${encodeURIComponent(subUrl)}&lang=${encodeURIComponent(item.lan || 'zh')}&type=${isAuto ? 'auto' : 'official'}`,
                type: isAuto ? 'auto' : 'official',
                isAutoGenerated: isAuto,
                isDanmaku: false,
                ext: 'json',
                author: item.author?.name || undefined,
              });
            }
          }
        }
      } catch (_) {}
    }

    // Priority 2: Standard Bilibili player v2 API fallback
    if (cid && tracks.length === 0) {
      try {
        const v2Res = await fetch(`https://api.bilibili.com/x/player/v2?bvid=${bvid}&cid=${cid}`, {
          headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
            'Referer': 'https://www.bilibili.com/',
            'Cookie': cookieHeader,
          },
          signal: AbortSignal.timeout(5000),
        });
        if (v2Res.ok) {
          const v2Json = await v2Res.json();
          const v2Subs = v2Json.data?.subtitle?.subtitles || [];
          for (const item of v2Subs) {
            if (item.subtitle_url && !tracks.some(t => t.url === item.subtitle_url || t.lang === item.lan)) {
              let subUrl = item.subtitle_url;
              if (subUrl.startsWith('//')) subUrl = `https:${subUrl}`;
              const isAuto = item.is_machine === 1 || item.lan_doc?.includes('自动') || item.lan_doc?.includes('AI') || item.lan?.includes('ai');
              const langName = item.lan_doc || item.lan || 'Tiếng Trung (Phụ đề gốc)';
              tracks.push({
                lang: item.lan || 'zh-CN',
                name: `${langName} ${isAuto ? '(AI Tự động)' : '(Phụ đề chuẩn)'}`,
                url: subUrl,
                downloadUrl: `/api/proxy-subtitle?url=${encodeURIComponent(subUrl)}&lang=${encodeURIComponent(item.lan || 'zh')}&type=${isAuto ? 'auto' : 'official'}`,
                type: isAuto ? 'auto' : 'official',
                isAutoGenerated: isAuto,
                isDanmaku: false,
                ext: 'json',
                author: item.author?.name || undefined,
              });
            }
          }
        }
      } catch (_) {}
    }

    return tracks;
  } catch (err: any) {
    console.warn('[Bilibili Subtitle API] Error fetching subtitles:', err.message);
    return [];
  }
}

/**
 * Direct YouTube timedtext caption extractor for Official (--write-subs) and Auto (--write-auto-subs)
 */
export async function fetchYouTubeOfficialSubtitles(urlOrVideoId: string): Promise<YtDlpSubtitleTrack[]> {
  try {
    let videoId = '';
    const vMatch = urlOrVideoId.match(/(?:v=|\/embed\/|\/v\/|youtu\.be\/|\/shorts\/)([a-zA-Z0-9_-]{11})/i);
    if (vMatch) {
      videoId = vMatch[1];
    } else if (urlOrVideoId.length === 11) {
      videoId = urlOrVideoId;
    }

    if (!videoId) return [];

    console.log(`[YouTube Subtitle API] Fetching captions for video ID: ${videoId}...`);
    const pageRes = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'vi,en;q=0.9',
      },
      signal: AbortSignal.timeout(6000),
    });

    if (!pageRes.ok) return [];
    const html = await pageRes.text();

    const captionMatch = html.match(/"captionTracks":\s*(\[[^\]]+\])/);
    if (!captionMatch || !captionMatch[1]) return [];

    const captionTracks = JSON.parse(captionMatch[1]);
    const tracks: YtDlpSubtitleTrack[] = [];

    for (const track of captionTracks) {
      if (track.baseUrl) {
        const isAuto = track.kind === 'asr' || track.vssId?.startsWith('a.');
        const langCode = track.languageCode || 'vi';
        const langName = track.name?.simpleText || track.name?.runs?.[0]?.text || langCode;

        tracks.push({
          lang: langCode,
          name: `${langName} ${isAuto ? '(AI Tự động)' : '(Phụ đề chuẩn)'}`,
          url: track.baseUrl,
          downloadUrl: `/api/proxy-subtitle?url=${encodeURIComponent(track.baseUrl)}&lang=${encodeURIComponent(langCode)}&type=${isAuto ? 'auto' : 'official'}`,
          type: isAuto ? 'auto' : 'official',
          isAutoGenerated: isAuto,
          isDanmaku: false,
          ext: 'srv3',
        });
      }
    }

    return tracks;
  } catch (err: any) {
    console.warn('[YouTube Subtitle API] Error fetching captions:', err.message);
    return [];
  }
}

/**
 * Extracts metadata, streaming links, and subtitles using yt-dlp
 */
export async function extractWithYtDlp(rawUrl: string): Promise<YtDlpExtractResult> {
  const targetUrl = await resolveCanonicalUrl(rawUrl);

  const binary = await ensureYtDlpBinary();
  const isBilibili = targetUrl.includes('bilibili.com') || targetUrl.includes('b23.tv');
  const isDouyin = targetUrl.includes('douyin.com') || targetUrl.includes('iesdouyin.com') || targetUrl.includes('snssdk.com');

  const args = [
    '--dump-json',
    '--no-playlist',
    '--no-warnings',
    '--no-check-certificates',
    '--write-subs',
    '--write-auto-subs',
    '--sub-langs',
    'all',
    '--sub-format',
    'srt/vtt/json/best',
    '--format',
    'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
    '--js-runtimes',
    'node',
    '--ffmpeg-location',
    '/usr/bin/ffmpeg',
  ];

  if (isBilibili) {
    const cookieFile = await ensureBilibiliCookieFile();
    args.push(
      '--cookies', cookieFile,
      '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
      '--referer', 'https://www.bilibili.com/'
    );
  } else if (isDouyin) {
    const cookieFile = await ensureDouyinCookieFile();
    args.push(
      '--cookies', cookieFile,
      '--user-agent', 'Mozilla/5.0 (Linux; Android 9; V2453A Build/PQ3A.190801.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.117 Mobile Safari/537.36',
      '--referer', 'https://www.douyin.com/'
    );
  }

  args.push(targetUrl);

  try {
    const { stdout } = await execFilePromise(binary, args, {
      timeout: 25000,
      maxBuffer: 10 * 1024 * 1024,
      env: {
        ...process.env,
        PYTHONUNBUFFERED: '1',
      }
    });

    if (!stdout || !stdout.trim()) {
      throw new Error('yt-dlp không trả về dữ liệu cho video này.');
    }

    const data = JSON.parse(stdout.trim());
    const formatsRaw: any[] = Array.isArray(data.formats) ? data.formats : [];

    const medias: YtDlpMediaFormat[] = [];
    const seenQualities = new Set<string>();

    // 1. Process Video Formats
    const videoFormats = formatsRaw
      .filter((f) => f.url && f.vcodec && f.vcodec !== 'none')
      .sort((a, b) => (b.height || 0) - (a.height || 0));

    for (const f of videoFormats) {
      const height = f.height || 0;
      let label = `${height}p`;
      if (height >= 2160) label = '4K (2160p)';
      else if (height >= 1440) label = '2K (1440p)';
      else if (height >= 1080) label = 'Full HD (1080p)';
      else if (height >= 720) label = 'HD (720p)';
      else if (height >= 480) label = 'SD (480p)';
      else if (height >= 360) label = '360p';

      const key = `${label}_${f.ext || 'mp4'}`;
      if (!seenQualities.has(key)) {
        seenQualities.add(key);
        medias.push({
          quality: label,
          extension: f.ext || 'mp4',
          url: f.url,
          directUrl: `/api/proxy-video?url=${encodeURIComponent(f.url)}`,
          size: formatBytes(f.filesize || f.filesize_approx),
          isAudioOnly: false,
          resolution: f.resolution || (height ? `${f.width || ''}x${height}` : undefined),
          fps: f.fps,
          formatId: f.format_id,
        });
      }
    }

    // 2. Process Audio Formats
    const audioFormats = formatsRaw
      .filter((f) => f.url && (f.vcodec === 'none' || !f.vcodec) && f.acodec && f.acodec !== 'none')
      .sort((a, b) => (b.abr || 0) - (a.abr || 0));

    for (const f of audioFormats) {
      const abr = Math.round(f.abr || 128);
      const ext = f.ext === 'webm' ? 'opus' : (f.ext || 'm4a');
      const label = `Audio ${ext.toUpperCase()} (${abr} kbps)`;
      const key = `audio_${ext}_${abr}`;

      if (!seenQualities.has(key) && medias.filter(m => m.isAudioOnly).length < 3) {
        seenQualities.add(key);
        medias.push({
          quality: label,
          extension: ext,
          url: f.url,
          directUrl: `/api/proxy-video?url=${encodeURIComponent(f.url)}`,
          size: formatBytes(f.filesize || f.filesize_approx),
          isAudioOnly: true,
          formatId: f.format_id,
        });
      }
    }

    // If requested single URL fallback
    if (medias.length === 0 && (data.url || (data.requested_formats && data.requested_formats[0]?.url))) {
      const primaryUrl = data.url || data.requested_formats[0].url;
      medias.push({
        quality: 'Video Chuẩn (MP4)',
        extension: 'mp4',
        url: primaryUrl,
        directUrl: `/api/proxy-video?url=${encodeURIComponent(primaryUrl)}`,
        isAudioOnly: false,
      });
    }

    // 3. Process Subtitles: Differentiate between [Phụ đề chuẩn / Official Subtitles], [Phụ đề tự động / Auto CC], and [Đạn mạc / Danmaku]
    const subtitles: YtDlpSubtitleTrack[] = [];
    const seenSubKeys = new Set<string>();

    const formatLangLabel = (code: string, rawName?: string): string => {
      const c = code.toLowerCase();
      if (c.startsWith('zh-hans') || c === 'zh-cn' || c === 'zh_cn' || c === 'ai-zh') return 'Tiếng Trung (Giản thể)';
      if (c.startsWith('zh-hant') || c === 'zh-tw' || c === 'zh-hk') return 'Tiếng Trung (Phồn thể)';
      if (c.startsWith('zh')) return 'Tiếng Trung';
      if (c.startsWith('vi')) return 'Tiếng Việt';
      if (c.startsWith('en')) return 'Tiếng Anh (English)';
      if (c.startsWith('ja')) return 'Tiếng Nhật (Japanese)';
      if (c.startsWith('ko')) return 'Tiếng Hàn (Korean)';
      if (c.startsWith('fr')) return 'Tiếng Pháp (French)';
      if (c.startsWith('es')) return 'Tiếng Tây Ban Nha (Spanish)';
      if (c.startsWith('ru')) return 'Tiếng Nga (Russian)';
      if (c.startsWith('de')) return 'Tiếng Đức (German)';
      if (c.startsWith('th')) return 'Tiếng Thái (Thai)';
      if (c.startsWith('id')) return 'Tiếng Indonesia';
      return rawName || code;
    };

    // A. Official Subtitles (Phụ đề chuẩn do uploader đăng tải)
    if (data.subtitles && typeof data.subtitles === 'object') {
      for (const [lang, trackList] of Object.entries(data.subtitles)) {
        if (Array.isArray(trackList) && trackList.length > 0) {
          // Check if this is danmaku
          const isDanmaku = lang.toLowerCase().includes('danmaku') || trackList.some((t: any) => t.ext === 'danmaku' || t.name?.toLowerCase()?.includes('danmaku'));
          
          const preferredTrack = trackList.find((t: any) => t.ext === 'srt' || t.ext === 'vtt' || t.ext === 'json') || trackList[0];
          if (preferredTrack && preferredTrack.url) {
            const subKey = `official_${lang}`;
            if (!seenSubKeys.has(subKey)) {
              seenSubKeys.add(subKey);
              const langName = formatLangLabel(lang, preferredTrack.name);
              subtitles.push({
                lang,
                name: isDanmaku ? `${langName} (Đạn mạc)` : `${langName} (Phụ đề chuẩn)`,
                url: preferredTrack.url,
                downloadUrl: `/api/proxy-subtitle?url=${encodeURIComponent(preferredTrack.url)}&lang=${encodeURIComponent(lang)}&type=${isDanmaku ? 'danmaku' : 'official'}`,
                type: isDanmaku ? 'danmaku' : 'official',
                isAutoGenerated: false,
                isDanmaku,
                ext: preferredTrack.ext || 'vtt',
              });
            }
          }
        }
      }
    }

    // B. Direct Bilibili API supplement (if Bilibili video)
    if (targetUrl.includes('bilibili.com') || targetUrl.includes('b23.tv') || data.extractor?.toLowerCase()?.includes('bili')) {
      try {
        const biliSubs = await fetchBilibiliOfficialSubtitles(targetUrl);
        for (const bs of biliSubs) {
          const subKey = `${bs.type}_${bs.lang}`;
          if (!seenSubKeys.has(subKey)) {
            seenSubKeys.add(subKey);
            subtitles.unshift(bs); // Give top priority to official Bilibili CC
          }
        }
      } catch (_) {}
    }

    // B2. Direct YouTube Subtitles supplement (if YouTube video)
    if (targetUrl.includes('youtube.com') || targetUrl.includes('youtu.be') || data.extractor?.toLowerCase()?.includes('youtube')) {
      try {
        const ytSubs = await fetchYouTubeOfficialSubtitles(targetUrl);
        for (const ys of ytSubs) {
          const subKey = `${ys.type}_${ys.lang}`;
          if (!seenSubKeys.has(subKey)) {
            seenSubKeys.add(subKey);
            if (ys.type === 'official') {
              subtitles.unshift(ys);
            } else {
              subtitles.push(ys);
            }
          }
        }
      } catch (_) {}
    }

    // C. Automatic Captions (Phụ đề AI nhận dạng tự động)
    if (data.automatic_captions && typeof data.automatic_captions === 'object') {
      for (const [lang, trackList] of Object.entries(data.automatic_captions)) {
        if (Array.isArray(trackList) && trackList.length > 0) {
          const preferredTrack = trackList.find((t: any) => t.ext === 'srt' || t.ext === 'vtt' || t.ext === 'json3' || t.ext === 'srv3') || trackList[0];
          if (preferredTrack && preferredTrack.url) {
            const subKey = `auto_${lang}`;
            if (!seenSubKeys.has(subKey) && !seenSubKeys.has(`official_${lang}`)) {
              seenSubKeys.add(subKey);
              const langName = formatLangLabel(lang, preferredTrack.name);
              subtitles.push({
                lang,
                name: `${langName} (AI Tự động)`,
                url: preferredTrack.url,
                downloadUrl: `/api/proxy-subtitle?url=${encodeURIComponent(preferredTrack.url)}&lang=${encodeURIComponent(lang)}&type=auto`,
                type: 'auto',
                isAutoGenerated: true,
                isDanmaku: false,
                ext: preferredTrack.ext || 'vtt',
              });
            }
          }
        }
      }
    }

    // D. Danmaku track (if present in danmaku field)
    if (data.danmaku && typeof data.danmaku === 'object') {
      for (const [lang, trackList] of Object.entries(data.danmaku)) {
        if (Array.isArray(trackList) && trackList.length > 0) {
          const track = trackList[0];
          if (track && track.url) {
            subtitles.push({
              lang: lang || 'danmaku',
              name: `Bình luận bay Danmaku (${lang})`,
              url: track.url,
              downloadUrl: `/api/proxy-subtitle?url=${encodeURIComponent(track.url)}&lang=danmaku&type=danmaku`,
              type: 'danmaku',
              isAutoGenerated: false,
              isDanmaku: true,
              ext: track.ext || 'xml',
            });
          }
        }
      }
    }

    const primaryVideo = medias.find(m => !m.isAudioOnly) || medias[0];
    const primaryAudio = medias.find(m => m.isAudioOnly);

    return {
      success: true,
      title: data.title || data.fulltitle || 'Video Tải Qua yt-dlp',
      thumbnail: data.thumbnail || (Array.isArray(data.thumbnails) && data.thumbnails.length > 0 ? data.thumbnails[data.thumbnails.length - 1].url : ''),
      duration: data.duration || 0,
      durationFormatted: formatDurationSeconds(data.duration),
      source: data.extractor || data.extractor_key || 'yt-dlp',
      author: data.uploader || data.channel || data.creator || undefined,
      views: data.view_count ? data.view_count.toLocaleString('vi-VN') : undefined,
      medias,
      subtitles: subtitles.slice(0, 30),
      videoUrl: primaryVideo?.url || '',
      directUrl: primaryVideo?.directUrl || primaryVideo?.url || '',
      audioUrl: primaryAudio?.url || '',
      audioDirectUrl: primaryAudio?.directUrl || primaryAudio?.url || '',
    };
  } catch (err: any) {
    const errMsg = err?.message || String(err);
    console.warn(`[yt-dlp Service] Direct extraction failed: ${errMsg}. Falling back to secondary extractors...`);
    
    // If Bilibili video and yt-dlp failed, try native direct Bilibili API
    if (isBilibili) {
      const directBili = await extractBilibiliDirect(targetUrl);
      if (directBili.success) {
        return directBili;
      }
      if (directBili.error && !directBili.error.startsWith('Lỗi bóc tách')) {
        return directBili;
      }
    }

    return await fallbackExtractVideo(targetUrl);
  }
}

/**
 * Resilient Fallback extractor for TikTok, Douyin, Cobalt API, and direct links
 */
export async function fallbackExtractVideo(cleanUrl: string): Promise<YtDlpExtractResult> {
  const resolvedUrl = await resolveCanonicalUrl(cleanUrl);
  let platform = 'video';
  if (resolvedUrl.includes('tiktok.com') || resolvedUrl.includes('douyin.com')) platform = 'tiktok';
  else if (resolvedUrl.includes('bilibili.com') || resolvedUrl.includes('b23.tv')) platform = 'bilibili';
  else if (resolvedUrl.includes('youtube.com') || resolvedUrl.includes('youtu.be')) platform = 'youtube';
  else if (resolvedUrl.includes('facebook.com') || resolvedUrl.includes('fb.watch')) platform = 'facebook';
  else if (resolvedUrl.includes('instagram.com')) platform = 'instagram';

  // 1. Direct Bilibili API Native fallback
  if (platform === 'bilibili') {
    const directResult = await extractBilibiliDirect(resolvedUrl);
    if (directResult.success || (directResult.error && !directResult.error.startsWith('Lỗi bóc tách'))) {
      return directResult;
    }
  }

  // 2. TikTok/Douyin via TikWM
  if (platform === 'tiktok') {
    try {
      const tikRes = await fetch(`https://www.tikwm.com/api/?url=${encodeURIComponent(resolvedUrl)}`, {
        headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' },
        signal: AbortSignal.timeout(6000),
      });
      if (tikRes.ok) {
        const tik = await tikRes.json();
        if (tik?.code === 0 && tik?.data) {
          const videoUrl = tik.data.play?.startsWith('http') ? tik.data.play : `https://www.tikwm.com${tik.data.play}`;
          const audioUrl = tik.data.music?.startsWith('http') ? tik.data.music : (tik.data.music ? `https://www.tikwm.com${tik.data.music}` : '');
          const medias: YtDlpMediaFormat[] = [
            {
              quality: 'HD No Watermark (MP4)',
              extension: 'mp4',
              url: videoUrl,
              directUrl: `/api/proxy-video?url=${encodeURIComponent(videoUrl)}`,
              isAudioOnly: false,
            }
          ];
          if (audioUrl) {
            medias.push({
              quality: 'Audio MP3',
              extension: 'mp3',
              url: audioUrl,
              directUrl: `/api/proxy-video?url=${encodeURIComponent(audioUrl)}`,
              isAudioOnly: true,
            });
          }
          return {
            success: true,
            title: tik.data.title || 'TikTok Video',
            thumbnail: tik.data.cover?.startsWith('http') ? tik.data.cover : (tik.data.cover ? `https://www.tikwm.com${tik.data.cover}` : ''),
            duration: tik.data.duration || 0,
            durationFormatted: formatDurationSeconds(tik.data.duration),
            source: 'TikTok (TikWM)',
            author: tik.data.author?.nickname || 'TikTok User',
            views: tik.data.play_count ? tik.data.play_count.toLocaleString('vi-VN') : undefined,
            medias,
            videoUrl,
            directUrl: `/api/proxy-video?url=${encodeURIComponent(videoUrl)}`,
            audioUrl,
            audioDirectUrl: audioUrl ? `/api/proxy-video?url=${encodeURIComponent(audioUrl)}` : undefined,
          };
        }
      }
    } catch (_) {}
  }

  // 3. Direct Video URL check
  if (resolvedUrl.match(/\.(mp4|webm|mov|m3u8)(\?.*)?$/i)) {
    const fileName = resolvedUrl.split('/').pop()?.split('?')[0] || 'Direct Video Stream';
    return {
      success: true,
      title: fileName,
      thumbnail: '',
      duration: 0,
      source: 'Direct URL',
      author: 'Direct',
      medias: [
        {
          quality: 'Direct Stream (MP4)',
          extension: 'mp4',
          url: resolvedUrl,
          directUrl: `/api/proxy-video?url=${encodeURIComponent(resolvedUrl)}`,
          isAudioOnly: false,
        }
      ],
      videoUrl: resolvedUrl,
      directUrl: `/api/proxy-video?url=${encodeURIComponent(resolvedUrl)}`,
    };
  }

  // 4. Cobalt API Fallback
  try {
    const cobaltRes = await fetch('https://api.cobalt.tools/api/json', {
      method: 'POST',
      headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },
      body: JSON.stringify({ url: resolvedUrl }),
      signal: AbortSignal.timeout(5000),
    });
    if (cobaltRes.ok) {
      const cob = await cobaltRes.json();
      const cobUrl = cob.url || cob.picker?.[0]?.url;
      if (cobUrl) {
        let fallbackSubs: YtDlpSubtitleTrack[] = [];
        if (resolvedUrl.includes('bilibili.com') || resolvedUrl.includes('b23.tv')) {
          try {
            fallbackSubs = await fetchBilibiliOfficialSubtitles(resolvedUrl);
          } catch (_) {}
        } else if (resolvedUrl.includes('youtube.com') || resolvedUrl.includes('youtu.be')) {
          try {
            fallbackSubs = await fetchYouTubeOfficialSubtitles(resolvedUrl);
          } catch (_) {}
        }

        return {
          success: true,
          title: `Video (${platform.toUpperCase()})`,
          thumbnail: '',
          duration: 0,
          source: `Cobalt (${platform})`,
          author: platform,
          medias: [
            {
              quality: 'HD Stream (MP4)',
              extension: 'mp4',
              url: cobUrl,
              directUrl: `/api/proxy-video?url=${encodeURIComponent(cobUrl)}`,
              isAudioOnly: false,
            }
          ],
          subtitles: fallbackSubs,
          videoUrl: cobUrl,
          directUrl: `/api/proxy-video?url=${encodeURIComponent(cobUrl)}`,
        };
      }
    }
  } catch (_) {}

  return {
    success: false,
    title: '',
    thumbnail: '',
    duration: 0,
    source: 'unknown',
    medias: [],
    error: 'yt-dlp và các máy chủ tải dự phòng không thể bóc tách video từ đường dẫn này (video có thể đã bị xóa, đặt riêng tư hoặc không tồn tại). Vui lòng kiểm tra lại link!',
  };
}

/**
 * Download video and audio streams simultaneously with proper CDN headers and mux them with ffmpeg (-c copy)
 */
export async function downloadAndMuxStreams(options: {
  videoUrl?: string;
  audioUrl?: string;
  isAudioOnly?: boolean;
  outputFilePath: string;
}): Promise<string> {
  const { videoUrl, audioUrl, isAudioOnly, outputFilePath } = options;

  const buildHeaders = (url: string): Record<string, string> => {
    const headers: Record<string, string> = {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    };
    if (url.includes('bilibili.com') || url.includes('akamaized.net') || url.includes('upos-') || url.includes('bilivideo')) {
      headers['Referer'] = 'https://www.bilibili.com/';
    } else if (url.includes('tiktok.com') || url.includes('tikwm')) {
      headers['Referer'] = 'https://www.tiktok.com/';
    } else if (url.includes('youtube.com') || url.includes('googlevideo.com')) {
      headers['Referer'] = 'https://www.youtube.com/';
    }
    return headers;
  };

  // Case 1: Audio only requested
  if (isAudioOnly) {
    const targetAudioUrl = audioUrl || videoUrl;
    if (!targetAudioUrl) throw new Error('No audio URL provided.');

    const headers = buildHeaders(targetAudioUrl);
    const res = await fetch(targetAudioUrl, { headers, signal: AbortSignal.timeout(60000) });
    if (!res.ok) throw new Error(`Failed to fetch audio stream: HTTP ${res.status}`);

    const buffer = Buffer.from(await res.arrayBuffer());
    const tempRaw = `/tmp/raw_audio_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
    fs.writeFileSync(tempRaw, buffer);

    try {
      // Convert to clean MP3 or copy if already mp3
      await execFilePromise('/usr/bin/ffmpeg', [
        '-y',
        '-i', tempRaw,
        '-vn',
        '-c:a', 'libmp3lame',
        '-q:a', '2',
        outputFilePath
      ]);
    } catch (_) {
      // Fallback: copy file directly
      fs.copyFileSync(tempRaw, outputFilePath);
    } finally {
      try { fs.unlinkSync(tempRaw); } catch (_) {}
    }
    return outputFilePath;
  }

  // Case 2: Both Video & Audio exist -> Fast FFmpeg Remux (-c copy)
  if (videoUrl && audioUrl && videoUrl !== audioUrl) {
    const vHeaders = buildHeaders(videoUrl);
    const aHeaders = buildHeaders(audioUrl);

    const [vRes, aRes] = await Promise.all([
      fetch(videoUrl, { headers: vHeaders, signal: AbortSignal.timeout(90000) }),
      fetch(audioUrl, { headers: aHeaders, signal: AbortSignal.timeout(90000) }),
    ]);

    if (!vRes.ok) throw new Error(`Failed to fetch video stream: HTTP ${vRes.status}`);
    if (!aRes.ok) throw new Error(`Failed to fetch audio stream: HTTP ${aRes.status}`);

    const vBuf = Buffer.from(await vRes.arrayBuffer());
    const aBuf = Buffer.from(await aRes.arrayBuffer());

    const tempV = `/tmp/v_${Date.now()}_${Math.random().toString(36).substring(2, 6)}.m4s`;
    const tempA = `/tmp/a_${Date.now()}_${Math.random().toString(36).substring(2, 6)}.m4s`;

    fs.writeFileSync(tempV, vBuf);
    fs.writeFileSync(tempA, aBuf);

    try {
      await execFilePromise('/usr/bin/ffmpeg', [
        '-y',
        '-i', tempV,
        '-i', tempA,
        '-c', 'copy',
        '-movflags', 'faststart',
        outputFilePath
      ]);
    } finally {
      try { fs.unlinkSync(tempV); } catch (_) {}
      try { fs.unlinkSync(tempA); } catch (_) {}
    }
    return outputFilePath;
  }

  // Case 3: Only Video URL exists
  if (videoUrl) {
    const vHeaders = buildHeaders(videoUrl);
    const vRes = await fetch(videoUrl, { headers: vHeaders, signal: AbortSignal.timeout(90000) });
    if (!vRes.ok) throw new Error(`Failed to fetch video stream: HTTP ${vRes.status}`);
    const vBuf = Buffer.from(await vRes.arrayBuffer());
    fs.writeFileSync(outputFilePath, vBuf);
    return outputFilePath;
  }

  throw new Error('No video or audio stream provided for muxing.');
}

/**
 * Execute yt-dlp to download and mux full video with audio via ffmpeg
 */
export async function executeYtDlpDownload(
  rawUrl: string,
  options: {
    formatId?: string;
    isAudioOnly?: boolean;
    outputFileTemplate: string;
  }
): Promise<string> {
  const cleanUrlMatch = rawUrl.match(/https?:\/\/[^\s]+/i);
  const targetUrl = cleanUrlMatch ? cleanUrlMatch[0] : rawUrl.trim();
  const binary = await ensureYtDlpBinary();
  const isBilibili = targetUrl.includes('bilibili.com') || targetUrl.includes('b23.tv');
  const isDouyin = targetUrl.includes('douyin.com') || targetUrl.includes('iesdouyin.com') || targetUrl.includes('snssdk.com');

  const args: string[] = [
    '--no-playlist',
    '--no-warnings',
    '--no-check-certificates',
    '--ffmpeg-location',
    '/usr/bin/ffmpeg',
    '--js-runtimes',
    'node',
  ];

  if (isBilibili) {
    const cookieFile = await ensureBilibiliCookieFile();
    args.push(
      '--cookies', cookieFile,
      '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
      '--referer', 'https://www.bilibili.com/'
    );
  } else if (isDouyin) {
    const cookieFile = await ensureDouyinCookieFile();
    args.push(
      '--cookies', cookieFile,
      '--user-agent', 'Mozilla/5.0 (Linux; Android 9; V2453A Build/PQ3A.190801.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.117 Mobile Safari/537.36',
      '--referer', 'https://www.douyin.com/'
    );
  }

  if (options.isAudioOnly) {
    args.push(
      '-x',
      '--audio-format', 'mp3',
      '--audio-quality', '0',
      '-o', options.outputFileTemplate,
      targetUrl
    );
  } else {
    // If formatId specified, merge that video stream with best audio stream
    const formatSpec = options.formatId
      ? `${options.formatId}+bestaudio/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best`
      : 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best';

    args.push(
      '-f', formatSpec,
      '--merge-output-format', 'mp4',
      '-o', options.outputFileTemplate,
      targetUrl
    );
  }

  await execFilePromise(binary, args, {
    timeout: 180000,
    maxBuffer: 50 * 1024 * 1024,
  });

  return options.outputFileTemplate;
}
