import { SubtitleItem, SubtitleStyleConfig, BlurOverlay, LogoOverlay, TextOverlay } from '../types';
import { wrapSubtitleText } from './srtParser';
import { generateVoiceoverAudioBuffer } from './audioExporter';
import { createFile as createMp4BoxFile, DataStream } from 'mp4box';
import fixWebmDuration from 'fix-webm-duration';
import { loadAllSavedCustomFonts, getSavedCustomFonts } from './fontStorage';
import { renderCompositedFrame } from './canvasRenderer';
import {
  Input,
  ALL_FORMATS,
  BufferSource,
  BufferTarget,
  Output,
  Mp4OutputFormat,
  CanvasSink,
  CanvasSource,
  AudioBufferSource,
  getFirstEncodableVideoCodec,
  getFirstEncodableAudioCodec,
} from 'mediabunny';

function createMp4File() {
  return createMp4BoxFile();
}

/**
 * Fixes duration metadata in MP4 files (mvhd, tkhd, mdhd, mehd boxes)
 * generated by MediaRecorder or encoders that omit or zero duration metadata.
 */
export async function fixMp4Duration(blob: Blob, durationInSeconds: number): Promise<Blob> {
  if (!durationInSeconds || durationInSeconds <= 0) return blob;

  try {
    const arrayBuffer = await blob.arrayBuffer();
    const bytes = new Uint8Array(arrayBuffer);
    const view = new DataView(arrayBuffer);

    let movieTimescale = 1000;

    function scanBoxes(start: number, end: number) {
      let pos = start;
      while (pos + 8 <= end) {
        let boxSize = view.getUint32(pos);
        const boxType = String.fromCharCode(
          bytes[pos + 4],
          bytes[pos + 5],
          bytes[pos + 6],
          bytes[pos + 7]
        );

        let headerSize = 8;
        if (boxSize === 1) {
          if (pos + 16 > end) break;
          const high = view.getUint32(pos + 8);
          const low = view.getUint32(pos + 12);
          boxSize = high * 4294967296 + low;
          headerSize = 16;
        } else if (boxSize === 0) {
          boxSize = end - pos;
        }

        if (boxSize < headerSize || pos + boxSize > end) {
          break;
        }

        const payloadStart = pos + headerSize;
        const payloadEnd = pos + boxSize;

        if (
          boxType === 'moov' ||
          boxType === 'trak' ||
          boxType === 'mdia' ||
          boxType === 'minf' ||
          boxType === 'mvex'
        ) {
          scanBoxes(payloadStart, payloadEnd);
        } else if (boxType === 'mvhd') {
          const version = bytes[payloadStart];
          let timescaleOffset = payloadStart + 12;
          let durationOffset = payloadStart + 16;
          if (version === 1) {
            timescaleOffset = payloadStart + 20;
            durationOffset = payloadStart + 24;
          }
          if (timescaleOffset + 4 <= payloadEnd) {
            movieTimescale = view.getUint32(timescaleOffset) || 1000;
          }
          const targetDurationUnits = Math.round(durationInSeconds * movieTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        } else if (boxType === 'tkhd') {
          const version = bytes[payloadStart];
          let durationOffset = payloadStart + 20;
          if (version === 1) {
            durationOffset = payloadStart + 28;
          }
          const targetDurationUnits = Math.round(durationInSeconds * movieTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        } else if (boxType === 'mdhd') {
          const version = bytes[payloadStart];
          let timescaleOffset = payloadStart + 12;
          let durationOffset = payloadStart + 16;
          if (version === 1) {
            timescaleOffset = payloadStart + 20;
            durationOffset = payloadStart + 24;
          }
          let mediaTimescale = movieTimescale;
          if (timescaleOffset + 4 <= payloadEnd) {
            mediaTimescale = view.getUint32(timescaleOffset) || movieTimescale;
          }
          const targetDurationUnits = Math.round(durationInSeconds * mediaTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        } else if (boxType === 'mehd') {
          const version = bytes[payloadStart];
          const durationOffset = payloadStart + 4;
          const targetDurationUnits = Math.round(durationInSeconds * movieTimescale);

          if (version === 0 && durationOffset + 4 <= payloadEnd) {
            view.setUint32(durationOffset, targetDurationUnits);
          } else if (version === 1 && durationOffset + 8 <= payloadEnd) {
            const high = Math.floor(targetDurationUnits / 4294967296);
            const low = targetDurationUnits % 4294967296;
            view.setUint32(durationOffset, high);
            view.setUint32(durationOffset + 4, low);
          }
        }

        pos += boxSize;
      }
    }

    scanBoxes(0, bytes.length);
    return new Blob([bytes.buffer], { type: blob.type || 'video/mp4' });
  } catch (err) {
    console.warn('[fixMp4Duration] Failed to patch MP4 duration:', err);
    return blob;
  }
}

/**
 * Adjusts volume of an AudioBuffer using OfflineAudioContext.
 */
async function adjustAudioBufferVolume(
  original: AudioBuffer | null,
  volume: number = 1.0,
  targetDuration: number
): Promise<AudioBuffer | null> {
  if (!original) return null;
  if (volume === 0) return null; // Muted
  if (volume === 1.0) return original; // No change needed

  const sampleRate = original.sampleRate;
  const numChannels = original.numberOfChannels;
  const duration = Math.max(original.duration, targetDuration);

  const offlineCtx = new OfflineAudioContext(
    numChannels,
    Math.ceil(sampleRate * duration),
    sampleRate
  );

  const originalSource = offlineCtx.createBufferSource();
  originalSource.buffer = original;

  const gainNode = offlineCtx.createGain();
  gainNode.gain.value = volume;

  originalSource.connect(gainNode);
  gainNode.connect(offlineCtx.destination);
  originalSource.start(0);

  return await offlineCtx.startRendering();
}

/**
 * Mixes original video audio and TTS voiceover audio together.
 */
async function mixAudioBuffers(
  original: AudioBuffer | null,
  tts: AudioBuffer | null,
  targetDuration: number,
  videoVolume: number = 1.0
): Promise<AudioBuffer | null> {
  if (!original && !tts) return null;
  if (original && !tts) {
    return await adjustAudioBufferVolume(original, videoVolume, targetDuration);
  }
  if (!original && tts) return tts;

  // Both original and TTS exist
  if (videoVolume === 0) {
    return tts;
  }

  const sampleRate = original!.sampleRate;
  const numChannels = Math.max(original!.numberOfChannels, tts!.numberOfChannels);
  const duration = Math.max(original!.duration, tts!.duration, targetDuration);

  const offlineCtx = new OfflineAudioContext(
    numChannels,
    Math.ceil(sampleRate * duration),
    sampleRate
  );

  // 1. Play original audio with videoVolume applied
  const originalSource = offlineCtx.createBufferSource();
  originalSource.buffer = original!;

  if (videoVolume !== 1.0) {
    const gainNode = offlineCtx.createGain();
    gainNode.gain.value = videoVolume;
    originalSource.connect(gainNode);
    gainNode.connect(offlineCtx.destination);
  } else {
    originalSource.connect(offlineCtx.destination);
  }
  originalSource.start(0);

  // 2. Play TTS audio (mono will be automatically upmixed to stereo/numChannels)
  const ttsSource = offlineCtx.createBufferSource();
  ttsSource.buffer = tts!;
  ttsSource.connect(offlineCtx.destination);
  ttsSource.start(0);

  return await offlineCtx.startRendering();
}

export interface RenderProgress {
  percentage: number;
  currentTime: number;
  duration: number;
  status: string;
}

/**
 * Draws current video frame and burning subtitle overlay onto the 2D Canvas context.
 */
function wrapCanvasText(
  context: CanvasRenderingContext2D,
  text: string,
  maxWidth: number
): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let currentLine = '';

  for (let i = 0; i < words.length; i++) {
    const word = words[i];
    const testLine = currentLine ? currentLine + ' ' + word : word;
    const metrics = context.measureText(testLine);
    if (metrics.width > maxWidth && i > 0) {
      lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }
  if (currentLine) {
    lines.push(currentLine);
  }
  return lines;
}

function getBgColorWithOpacity(hexColor: string, opacity: number = 65): string {
  if (!hexColor) return `rgba(0, 0, 0, ${opacity / 100})`;
  if (hexColor.startsWith('rgba')) return hexColor;
  let hex = hexColor.replace('#', '');
  if (hex.length === 3) hex = hex.split('').map(x => x + x).join('');
  const num = parseInt(hex, 16);
  if (isNaN(num)) return `rgba(0, 0, 0, ${opacity / 100})`;
  const r = (num >> 16) & 255;
  const g = (num >> 8) & 255;
  const b = num & 255;
  return `rgba(${r}, ${g}, ${b}, ${(opacity / 100).toFixed(2)})`;
}

export function drawSubtitleOverlay(
  ctx: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D,
  video: HTMLVideoElement | HTMLCanvasElement | OffscreenCanvas | ImageBitmap | VideoFrame,
  vWidth: number,
  vHeight: number,
  curTime: number,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  blurOverlays: BlurOverlay[] = [],
  logoOverlays: LogoOverlay[] = [],
  textOverlays: TextOverlay[] = [],
  logoBitmaps: Record<string, HTMLImageElement | ImageBitmap> = {}
) {
  renderCompositedFrame(ctx, {
    videoSource: video,
    vWidth,
    vHeight,
    curTime,
    subtitles,
    styleConfig,
    blurOverlays,
    logoOverlays,
    textOverlays,
    logoBitmaps,
  });
}

/**
 * Renders video with subtitles using Mediabunny CanvasSink, CanvasSource, AudioBufferSource, and Mp4OutputFormat.
 * Guarantees zero tearing, perfect PTS/DTS sync, and hardware-accelerated encoding with fallback.
 */
export async function renderWithMp4Muxer(
  videoUrl: string,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  onProgress: (progress: RenderProgress) => void,
  options: {
    blurOverlays?: BlurOverlay[];
    logoOverlays?: LogoOverlay[];
    textOverlays?: TextOverlay[];
    includeVoiceover?: boolean;
    ttsSpeed?: number;
    ttsPitch?: number;
    videoVolume?: number;
    targetWidth?: number;
    targetHeight?: number;
    fps?: number;
    bitrate?: number;
  } = {},
  preferSoftware = false
): Promise<Blob> {
  if (typeof VideoEncoder === 'undefined') {
    throw new Error('WebCodecs VideoEncoder không được hỗ trợ trên trình duyệt này.');
  }

  // Preload and ensure all fonts (Google Fonts & custom uploaded fonts) are ready
  try {
    await loadAllSavedCustomFonts();
    if (typeof document !== 'undefined' && document.fonts) {
      await document.fonts.ready;
    }
  } catch (_fontErr) {}

  if (!styleConfig.customUploadedFonts || styleConfig.customUploadedFonts.length === 0) {
    const savedFonts = getSavedCustomFonts();
    if (savedFonts.length > 0) {
      styleConfig = {
        ...styleConfig,
        customUploadedFonts: savedFonts
          .filter((f) => f.dataUrl)
          .map((f) => ({
            family: f.value.split(',')[0].replace(/['"]/g, '').trim(),
            dataUrl: f.dataUrl!,
          })),
      };
    }
  }

  // 1. Fetch the video as an ArrayBuffer
  let arrayBuffer: ArrayBuffer;
  try {
    const res = await fetch(videoUrl);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    arrayBuffer = await res.arrayBuffer();
  } catch (err) {
    throw new Error(`CORS hoặc network error khi tải video: ${String(err)}`);
  }

  // 2. Preload Logo Overlays
  const logoBitmaps = await preloadLogoOverlays(options.logoOverlays || []);

  // 3. Demux video using Mediabunny Input
  const input = new Input({
    formats: ALL_FORMATS,
    source: new BufferSource(arrayBuffer),
  });

  const videoTrack = await input.getPrimaryVideoTrack();
  if (!videoTrack) {
    throw new Error('Không tìm thấy luồng Video Track trong tệp video nguồn.');
  }

  const rawDuration = await input.computeDuration();
  const duration = rawDuration || 10;
  const packetStats = await videoTrack.computePacketStats(150);

  let videoFps = (packetStats && packetStats.averagePacketRate > 0)
    ? packetStats.averagePacketRate
    : 30;

  if (options.fps && options.fps > 0) {
    videoFps = options.fps;
  } else if (!videoFps || !isFinite(videoFps) || videoFps <= 5 || videoFps > 120) {
    videoFps = Math.max(10, Math.min(60, (packetStats?.packetCount || 0) / duration)) || 30;
  }

  const totalFrames = (packetStats && packetStats.packetCount > 0)
    ? packetStats.packetCount
    : Math.max(1, Math.round(duration * videoFps));

  const toEven = (val: number) => Math.max(2, Math.floor(val / 2) * 2);
  const trackWidth = videoTrack.displayWidth || videoTrack.codedWidth || 1280;
  const trackHeight = videoTrack.displayHeight || videoTrack.codedHeight || 720;
  const vWidth = toEven(options.targetWidth || trackWidth);
  const vHeight = toEven(options.targetHeight || trackHeight);

  // 4. Decode Original Audio (if present)
  let originalAudioBuffer: AudioBuffer | null = null;
  try {
    const actx = new (window.AudioContext || (window as any).webkitAudioContext)();
    const decodeBuf = arrayBuffer.slice(0);
    originalAudioBuffer = await actx.decodeAudioData(decodeBuf);
    await actx.close();
  } catch (e) {
    console.warn('Không có hoặc không thể nạp audio track gốc:', e);
  }

  // 5. Generate or Mix Audio
  const videoVolume = options.videoVolume ?? 1.0;
  let audioBuffer: AudioBuffer | null = null;
  if (options.includeVoiceover) {
    try {
      const result = await generateVoiceoverAudioBuffer(
        subtitles,
        duration,
        options.ttsSpeed || 1.0,
        options.ttsPitch || 0
      );
      const ttsAudioBuffer = result.buffer;
      audioBuffer = await mixAudioBuffers(originalAudioBuffer, ttsAudioBuffer, duration, videoVolume);
    } catch (e: any) {
      console.warn('Không thể dựng audio thuyết minh, sẽ dùng audio gốc làm fallback:', e);
      audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
    }
  } else {
    audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
  }

  // 6. Setup Mediabunny Output, BufferTarget, CanvasSink & CanvasSource
  const target = new BufferTarget();
  const output = new Output({
    format: new Mp4OutputFormat({ fastStart: 'in-memory' }),
    target,
  });

  const getDynamicBitrate = (width: number, height: number): number => {
    const pixels = width * height;
    if (pixels >= 3840 * 2160) return 20_000_000; // 4K -> 20 Mbps
    if (pixels >= 2560 * 1440) return 10_000_000; // 2K -> 10 Mbps
    if (pixels >= 1920 * 1080) return 5_000_000;  // 1080p -> 5 Mbps
    if (pixels >= 1280 * 720) return 2_500_000;   // 720p -> 2.5 Mbps
    return 1_200_000;                             // 480p/lower -> 1.2 Mbps
  };
  const dynamicBitrate = options.bitrate && options.bitrate > 0
    ? options.bitrate
    : getDynamicBitrate(vWidth, vHeight);

  // Determine encodable video codec
  const encodableVideoCodec = (await getFirstEncodableVideoCodec(['avc', 'hevc', 'vp9', 'av1'])) || 'avc';

  // Create render canvas
  const canvas = document.createElement('canvas');
  canvas.width = vWidth;
  canvas.height = vHeight;
  const ctx = canvas.getContext('2d', { willReadFrequently: false });
  if (!ctx) {
    throw new Error('Không thể khởi tạo 2D Context cho Canvas render.');
  }

  const canvasSource = new CanvasSource(canvas, {
    codec: encodableVideoCodec,
    bitrate: dynamicBitrate,
    keyFrameInterval: 2,
    hardwareAcceleration: preferSoftware ? 'prefer-software' : 'no-preference',
  });
  output.addVideoTrack(canvasSource);

  let audioSource: AudioBufferSource | null = null;
  if (audioBuffer) {
    const encodableAudioCodec = (await getFirstEncodableAudioCodec(['aac', 'opus'])) || 'aac';
    audioSource = new AudioBufferSource({
      codec: encodableAudioCodec,
      bitrate: 128_000,
    });
    output.addAudioTrack(audioSource);
  }

  await output.start();

  if (audioSource && audioBuffer) {
    await audioSource.add(audioBuffer);
    audioSource.close();
  }

  // Setup CanvasSink to decode source frames
  const canvasSink = new CanvasSink(videoTrack, {
    width: vWidth,
    height: vHeight,
    fit: 'fill',
    decoderOptions: {
      hardwareAcceleration: preferSoftware ? 'prefer-software' : 'no-preference',
    },
  });

  let frameIdx = 0;
  for await (const wrapped of canvasSink.canvases()) {
    // 1. Draw base video frame
    ctx.drawImage(wrapped.canvas, 0, 0, vWidth, vHeight);

    // 2. Draw overlays (Subtitles, Blur, Logos, Text)
    drawSubtitleOverlay(
      ctx,
      wrapped.canvas as any,
      vWidth,
      vHeight,
      wrapped.timestamp,
      subtitles,
      styleConfig,
      options.blurOverlays,
      options.logoOverlays,
      options.textOverlays,
      logoBitmaps
    );

    // 3. Add to canvasSource
    await canvasSource.add(wrapped.timestamp, wrapped.duration);

    frameIdx++;
    if (frameIdx % 4 === 0 || frameIdx === totalFrames) {
      const pct = Math.min(99, Math.round((frameIdx / totalFrames) * 100));
      onProgress({
        percentage: pct,
        currentTime: wrapped.timestamp,
        duration,
        status: `Đang xuất video chuẩn studio... (${pct}%)`,
      });
    }
  }

  canvasSource.close();
  await output.finalize();

  const finalMp4Blob = new Blob([target.buffer!], { type: 'video/mp4' });
  return finalMp4Blob;
}

async function preloadLogoOverlays(logoOverlays: LogoOverlay[]): Promise<Record<string, HTMLImageElement>> {
  const logoBitmaps: Record<string, HTMLImageElement> = {};
  await Promise.all(
    logoOverlays.map(async (logo) => {
      try {
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.src = logo.url;
        await new Promise((resolve, reject) => {
          img.onload = resolve;
          img.onerror = reject;
        });
        logoBitmaps[logo.id] = img;
        logoBitmaps[logo.url] = img;
      } catch (err) {
        console.warn(`[Preload Logos] Unable to preload logo from ${logo.url}:`, err);
      }
    })
  );
  return logoBitmaps;
}

/**
 * Fallback recorder using standard browser MediaRecorder API (WebM/MP4).
 */
export async function renderWithMediaRecorder(
  videoUrl: string,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  onProgress: (progress: RenderProgress) => void,
  options: {
    blurOverlays?: BlurOverlay[];
    logoOverlays?: LogoOverlay[];
    textOverlays?: TextOverlay[];
    includeVoiceover?: boolean;
    ttsSpeed?: number;
    ttsPitch?: number;
    videoVolume?: number;
    preferredFormat?: 'mp4' | 'webm';
  } = {}
): Promise<Blob> {
  return new Promise(async (resolve, reject) => {
    const video = document.createElement('video');
    if (videoUrl && !videoUrl.startsWith('blob:')) {
      video.crossOrigin = 'anonymous';
    }
    video.src = videoUrl;
    video.muted = true; // Mute video element to guarantee video.play() never gets blocked by autoplay policy

    // Preload and ensure all fonts (Google Fonts & custom uploaded fonts) are ready
    try {
      await loadAllSavedCustomFonts();
      if (typeof document !== 'undefined' && document.fonts) {
        await document.fonts.ready;
      }
    } catch (_fontErr) {}

    // Preload logo images for MediaRecorder canvas overlay
    const logoBitmaps = options.logoOverlays ? await preloadLogoOverlays(options.logoOverlays) : {};

    video.onloadedmetadata = async () => {
      try {
        const vWidth = video.videoWidth || 1280;
        const vHeight = video.videoHeight || 720;
        const duration = video.duration || 10;

        const canvas = document.createElement('canvas');
        canvas.width = vWidth;
        canvas.height = vHeight;
        const ctx = canvas.getContext('2d');

        if (!ctx) {
          reject(new Error('Không thể khởi tạo Canvas 2D'));
          return;
        }

        // Fetch original audio track and decode it
        let originalAudioBuffer: AudioBuffer | null = null;
        try {
          const res = await fetch(videoUrl);
          if (res.ok) {
            const arrBuf = await res.arrayBuffer();
            const actx = new (window.AudioContext || (window as any).webkitAudioContext)();
            originalAudioBuffer = await actx.decodeAudioData(arrBuf);
            await actx.close();
          }
        } catch (e) {
          console.warn('[MediaRecorder Fallback] Không có hoặc không nạp được audio track gốc:', e);
        }

        // Synthesize and mix voiceover audio track if requested
        const videoVolume = options.videoVolume ?? 1.0;
        let audioBuffer: AudioBuffer | null = null;
        if (options.includeVoiceover) {
          try {
            const result = await generateVoiceoverAudioBuffer(
              subtitles,
              duration,
              options.ttsSpeed || 1.0,
              options.ttsPitch || 0
            );
            const ttsAudioBuffer = result.buffer;
            audioBuffer = await mixAudioBuffers(originalAudioBuffer, ttsAudioBuffer, duration, videoVolume);
          } catch (e) {
            console.warn('[MediaRecorder Fallback] Không thể dựng audio thuyết minh, sẽ dùng audio gốc:', e);
            audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
          }
        } else {
          audioBuffer = await adjustAudioBufferVolume(originalAudioBuffer, videoVolume, duration);
        }

        const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
        const audioCtx = new AudioCtx();
        const dest = audioCtx.createMediaStreamDestination();

        // Ensure the AudioContext is running (important inside sandboxed iframes)
        if (audioCtx.state === 'suspended') {
          await audioCtx.resume();
        }

        let audioSourceNode: AudioBufferSourceNode | null = null;
        if (audioBuffer) {
          audioSourceNode = audioCtx.createBufferSource();
          audioSourceNode.buffer = audioBuffer;
          audioSourceNode.connect(dest);
        }

        const canvasStream = canvas.captureStream(30);
        const combinedTracks: MediaStreamTrack[] = [...canvasStream.getVideoTracks()];
        if (audioBuffer) {
          combinedTracks.push(...dest.stream.getAudioTracks());
        }
        const combinedStream = new MediaStream(combinedTracks);

        let mimeType = '';
        const prefFormat = options.preferredFormat || 'mp4';

        if (prefFormat === 'mp4') {
          if (MediaRecorder.isTypeSupported('video/mp4;codecs=h264,aac')) {
            mimeType = 'video/mp4;codecs=h264,aac';
          } else if (MediaRecorder.isTypeSupported('video/mp4')) {
            mimeType = 'video/mp4';
          }
        }

        if (!mimeType) {
          if (MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')) {
            mimeType = 'video/webm;codecs=vp9,opus';
          } else if (MediaRecorder.isTypeSupported('video/webm;codecs=vp8,opus')) {
            mimeType = 'video/webm;codecs=vp8,opus';
          } else if (MediaRecorder.isTypeSupported('video/webm')) {
            mimeType = 'video/webm';
          } else if (MediaRecorder.isTypeSupported('video/mp4;codecs=h264,aac')) {
            mimeType = 'video/mp4;codecs=h264,aac';
          } else if (MediaRecorder.isTypeSupported('video/mp4')) {
            mimeType = 'video/mp4';
          }
        }

        const recorderOptions = mimeType ? { mimeType } : undefined;
        const recorder = new MediaRecorder(combinedStream, recorderOptions);
        const chunks: Blob[] = [];

        recorder.ondataavailable = (e) => {
          if (e.data && e.data.size > 0) {
            chunks.push(e.data);
          }
        };

        recorder.onstop = async () => {
          if (audioSourceNode) {
            try { audioSourceNode.stop(); } catch {}
          }
          const finalType = mimeType || 'video/webm';
          const rawBlob = new Blob(chunks, { type: finalType });
          const durationMs = Math.max(1000, Math.round(duration * 1000));
          const durationSec = duration;

          if (finalType.includes('webm')) {
            try {
              fixWebmDuration(rawBlob, durationMs, (fixedBlob) => {
                resolve(fixedBlob);
              });
              return;
            } catch (fixErr) {
              console.warn('[MediaRecorder] Failed to fix webm duration header:', fixErr);
            }
          } else if (finalType.includes('mp4')) {
            try {
              const fixedBlob = await fixMp4Duration(rawBlob, durationSec);
              resolve(fixedBlob);
              return;
            } catch (fixErr) {
              console.warn('[MediaRecorder] Failed to fix mp4 duration header:', fixErr);
            }
          }
          resolve(rawBlob);
        };

        recorder.onerror = (err) => {
          reject(err);
        };

        const renderFrame = () => {
          const curTime = video.currentTime;
          const pct = Math.min(100, Math.round((curTime / duration) * 100));

          onProgress({
            percentage: pct,
            currentTime: curTime,
            duration,
            status: `Đang render video... (${pct}%)`,
          });

          drawSubtitleOverlay(
            ctx,
            video,
            vWidth,
            vHeight,
            curTime,
            subtitles,
            styleConfig,
            options.blurOverlays,
            options.logoOverlays,
            options.textOverlays,
            logoBitmaps
          );

          if (!video.ended && video.currentTime < duration) {
            requestAnimationFrame(renderFrame);
          } else {
            setTimeout(() => {
              if (recorder.state === 'recording') {
                recorder.stop();
              }
            }, 300);
          }
        };

        recorder.start(1000); // Pass timeslice to record chunks progressively and prevent Infinity duration issues
        
        video.play().then(() => {
          if (audioSourceNode) {
            audioSourceNode.start(0);
          }
          renderFrame();
        }).catch((playErr) => {
          console.error('[MediaRecorder Fallback] video.play() failed:', playErr);
          reject(new Error(`Không thể phát video để ghi hình: ${playErr.message}`));
        });

        video.onended = () => {
          setTimeout(() => {
            if (recorder.state === 'recording') {
              recorder.stop();
            }
          }, 300);
        };
      } catch (err) {
        reject(err);
      }
    };

    video.onerror = () => {
      reject(new Error('Không thể tải video nguồn để render.'));
    };
  });
}

/**
 * Main export video entry point. Uses mp4-muxer for MP4 format when supported,
 * with graceful fallback to MediaRecorder.
 */
export async function renderVideoWithSubtitles(
  videoUrl: string,
  subtitles: SubtitleItem[],
  styleConfig: SubtitleStyleConfig,
  onProgress: (progress: RenderProgress) => void,
  preferredFormat: 'mp4' | 'webm' | 'mediarecorder' = 'mp4',
  options: {
    blurOverlays?: BlurOverlay[];
    logoOverlays?: LogoOverlay[];
    textOverlays?: TextOverlay[];
    includeVoiceover?: boolean;
    ttsSpeed?: number;
    ttsPitch?: number;
    videoVolume?: number;
    targetWidth?: number;
    targetHeight?: number;
    fps?: number;
    bitrate?: number;
  } = {}
): Promise<{ blob: Blob; formatUsed: 'mp4' | 'webm' }> {
  if (preferredFormat === 'mp4' && typeof VideoEncoder !== 'undefined') {
    try {
      const blob = await renderWithMp4Muxer(videoUrl, subtitles, styleConfig, onProgress, options, false);
      return { blob, formatUsed: 'mp4' };
    } catch (err: any) {
      console.warn('[Mediabunny] GPU/HW rendering failed, retrying with Software Encoder (prefer-software)...', err);
      onProgress({
        percentage: 0,
        currentTime: 0,
        duration: 1,
        status: 'GPU encoder gián đoạn, đang tự động thử lại bằng Software Encoder (CPU)...',
      });
      try {
        const blob = await renderWithMp4Muxer(videoUrl, subtitles, styleConfig, onProgress, options, true);
        return { blob, formatUsed: 'mp4' };
      } catch (retryErr: any) {
        console.warn('[Mediabunny] Software rendering failed too, falling back to MediaRecorder:', retryErr);
        onProgress({
          percentage: 0,
          currentTime: 0,
          duration: 1,
          status: 'Chuyển sang MediaRecorder fallback...',
        });
      }
    }
  }

  const blob = await renderWithMediaRecorder(videoUrl, subtitles, styleConfig, onProgress, {
    ...options,
    preferredFormat: preferredFormat === 'webm' ? 'webm' : 'mp4',
  });
  const formatUsed = blob.type.includes('mp4') ? 'mp4' : 'webm';
  return { blob, formatUsed };
}
